const express = require("express");
const router = express.Router();
const { signup, login, logout } = require("../controllers/Authentication/user");
const { forgot, resetPassword } = require("../controllers/forgot");
const { uploadimage } = require("../controllers/image");
const { upload } = require("../controllers/image");
const { create, update, findall, find } = require("../controllers/update");
const { del, delall } = require("../controllers/status");
const { otpsignup, otplogin, otplogout } = require("../controllers/otp");
const { passport } = require("../controllers/googleauth");
const { passport1 } = require("../controllers/facebokaut");
router.post("/signup", signup);
router.post("/login", login);
router.post("/logout", logout);
router.post("/forgot", forgot);
router.post("/resetPassword/:userId/:token", resetPassword);
router.post("/uploadimage/:id", upload, uploadimage);
router.post("/otpsignup", otpsignup);
router.post("/otplogin", otplogin);
router.post("/otplogout", otplogout);
router.post("/createuser", create);
router.put("/update/:id", update);
router.put("/delete/:id", del);
router.get("/users", findall);
router.get("/user/:id", find);
router.put("/deleteall", delall);
router.get("/auth/google", passport);
router.get("/auth/google/callback", passport);
router.get("/auth/facebook", passport1);
router.get("/auth/facebook/callback", passport1);
module.exports = router;
